### ISSUE TITLE
`find_value` is not in `__init__.py`, so example on Pypi doesn't work

### ISSUE THREAD

**Issue by NodeJSmith** [ctomkow/jsonparse#34]
The example on pypi shows importing find_value along with the other methods directly from jsonparse. However, it looks like `find_value` was not added to `__init__.py`, so it can't be imported from here. It has to be imported from jsonparse.functions.

**Comment by ctomkow** [comment]
Thank you for the bug report!

I have released a [v0.14.1](https://github.com/ctomkow/jsonparse/releases/tag/0.14.1) that fixes this issue. 0.14.1 is on PyPi now as well.

Cheers.
